# Generated by Django 2.2.4 on 2020-06-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('estrellas', models.IntegerField()),
                ('comentario', models.TextField()),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
